[package]
name = "web_app"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
askama= "0.12"
askama_actix = "0.14"
sqlx = { version = "0.7.3", features = ["sqlite", "runtime-tokio"]}
idna = "0.3"
serde = { version = "1.0.215", features = ["derive"] }
